/**
 * Standalone MCMAP + Krav Maga practice tracks.
 * Separate from Cali-Tai calisthenics/tai chi plans.
 * Educational only — not certification, not a substitute for certified instructors.
 */
window.MARTIAL = {
  mcmap: {
    id: "mcmap",
    title: "Marine Corps Martial Arts (MCMAP)",
    shortTitle: "MCMAP",
    tagline: "Fundamentals, conditioning, and warrior ethos—practice, not a belt course.",
    blurb:
      "These pages are a civilian study aid inspired by publicly described MCMAP fundamentals (stance, movement, sustainment conditioning). They do not certify belts and do not replace training under a Martial Arts Instructor (MAI) or Instructor-Trainer (MAIT).",
    sources: [
      {
        id: "mco-1500",
        title: "MCO 1500.59A — Marine Corps Martial Arts Program",
        org: "U.S. Marine Corps",
        url: "https://www.marines.mil/News/Publications/MCPEL/Electronic-Library-Display/Article/899428/mco-150059a/",
        note: "Defines MCMAP management; training is conducted through certified instructors.",
      },
      {
        id: "mco-pdf",
        title: "MCO 1500.59 (PDF portal copy)",
        org: "U.S. Marine Corps",
        url: "https://www.marines.mil/portals/1/publications/mco%201500.59.pdf",
        note: "Program philosophy: mental, character, and physical disciplines.",
      },
      {
        id: "dvids-intro",
        title: "Introduction to MCMAP",
        org: "DVIDS / USMC",
        url: "https://www.dvidshub.net/news/404195/introduction-mcmap",
        note: "Public overview of tan-belt fundamentals, tie-ins, and instructor roles.",
      },
      {
        id: "marines-tv-ma",
        title: "Marines TV — Martial Arts videos",
        org: "U.S. Marine Corps",
        url: "https://www.marines.mil/News/Marines-TV/videoid/925336/dvpTag/Martial-Arts/",
        note: "Official footage of MCMAP training environments (not a full syllabus).",
      },
      {
        id: "cdc-adults",
        title: "Adult Activity Overview",
        org: "CDC",
        url: "https://www.cdc.gov/physical-activity-basics/guidelines/adults.html",
        note: "General activity safety baseline for conditioning work.",
      },
    ],
    howTos: [
      {
        id: "mcmap-lima",
        type: "video",
        title: "Lima Company MCMAP (tan belt training footage)",
        org: "DVIDS / USMC",
        url: "https://www.dvidshub.net/video/953029/lima-company-mcmap",
      },
      {
        id: "mcmap-india",
        type: "video",
        title: "India Company MCMAP (tan belt techniques footage)",
        org: "DVIDS / USMC",
        url: "https://www.dvidshub.net/video/1008962/india-company-mcmap",
      },
      {
        id: "mcmap-hotel",
        type: "video",
        title: "Hotel Company MCMAP (Parris Island training)",
        org: "Marines TV / USMC",
        url: "https://www.marines.mil/News/Marines-TV/videoid/860210/dvpyear/2022/?dvpTag=martial+arts",
      },
      {
        id: "ace-plank",
        type: "article",
        title: "Front plank (conditioning)",
        org: "ACE Exercise Library",
        url: "https://www.acefitness.org/resources/everyone/exercise-library/32/front-plank/",
      },
      {
        id: "ace-squat",
        type: "article",
        title: "Bodyweight squat (conditioning)",
        org: "ACE Exercise Library",
        url: "https://www.acefitness.org/resources/everyone/exercise-library/135/bodyweight-squat/",
      },
      {
        id: "ace-pushup",
        type: "article",
        title: "Push-up (conditioning)",
        org: "ACE Exercise Library",
        url: "https://www.acefitness.org/resources/everyone/exercise-library/41/push-up/",
      },
      {
        id: "mayo-warmup",
        type: "article",
        title: "How to warm up and cool down",
        org: "Mayo Clinic",
        url: "https://www.mayoclinic.org/healthy-lifestyle/fitness/in-depth/exercise/art-20045517",
      },
      {
        id: "dvids-intro-howto",
        type: "article",
        title: "Introduction to MCMAP (fundamentals context)",
        org: "DVIDS / USMC",
        url: "https://www.dvidshub.net/news/404195/introduction-mcmap",
      },
      {
        id: "mco-pdf",
        type: "article",
        title: "MCO 1500.59 program order (PDF)",
        org: "U.S. Marine Corps",
        url: "https://www.marines.mil/portals/1/publications/mco%201500.59.pdf",
      },
    ],
    safetyBullets: [
      "This track is educational practice support only. It does not award MCMAP belts and is not an official Marine Corps course.",
      "Contact techniques, throws, chokes, weapons work, and sparring require a certified Martial Arts Instructor (MAI/MAIT) and proper safety controls (MCO 1500.59A).",
      "Solo sessions here emphasize stance, footwork, shadow striking in air, and general conditioning—stop if you feel sharp pain, dizziness, or joint stress.",
      "If you have injuries or medical conditions, get clinical clearance before combatives-style conditioning.",
      "Never practice techniques on another person without qualified supervision and consent.",
    ],
    exercises: {
      march: {
        name: "Easy march + joint circles",
        kind: "warmup",
        cue: "2–3 minutes easy movement; ankles, hips, shoulders loose.",
        howToIds: ["mayo-warmup"],
      },
      warriorStance: {
        name: "Basic warrior stance hold",
        kind: "fundamentals",
        cue: "Balanced feet, soft knees, hands up, chin tucked. Study official footage; refine under an MAI.",
        howToIds: ["mcmap-lima", "dvids-intro-howto"],
      },
      anglesMove: {
        name: "Angles of movement (shadow footwork)",
        kind: "fundamentals",
        cue: "Step offline on diagonal angles; reset to stance. Slow and deliberate—no partner contact.",
        howToIds: ["mcmap-india", "dvids-intro-howto"],
      },
      shadowLead: {
        name: "Lead-hand shadow strikes (air only)",
        kind: "fundamentals",
        cue: "Relaxed shoulders; snap and return to guard. Do not strike hard surfaces.",
        howToIds: ["mcmap-hotel", "mcmap-lima"],
      },
      shadowRear: {
        name: "Rear-hand shadow strikes (air only)",
        kind: "fundamentals",
        cue: "Rotate hips gently; keep balance. Air only.",
        howToIds: ["mcmap-hotel", "mcmap-lima"],
      },
      comboShadow: {
        name: "Short combination shadow (1–2–guard)",
        kind: "fundamentals",
        cue: "Two-to-four strike strings ending in stance. Smooth, not sloppy fast.",
        howToIds: ["mcmap-india", "mcmap-lima"],
      },
      stanceSwitch: {
        name: "Stance switches + pivots",
        kind: "fundamentals",
        cue: "Change leads cleanly; eyes up. Use a mirror if available.",
        howToIds: ["mcmap-lima", "dvids-intro-howto"],
      },
      ethicsRead: {
        name: "Character / mental discipline review",
        kind: "ethos",
        cue: "Read a short section of MCO guidance or DVIDS intro; jot one leadership takeaway.",
        howToIds: ["dvids-intro-howto", "mco-pdf"],
      },
      pushCond: {
        name: "Push-up conditioning",
        kind: "conditioning",
        cue: "Quality reps; regress to incline/knee as needed.",
        howToIds: ["ace-pushup"],
      },
      squatCond: {
        name: "Squat conditioning",
        kind: "conditioning",
        cue: "Controlled depth; knees track over mid-foot.",
        howToIds: ["ace-squat"],
      },
      plankCond: {
        name: "Plank hold",
        kind: "conditioning",
        cue: "Rigid line; breathe steadily.",
        howToIds: ["ace-plank"],
      },
      burpeeLite: {
        name: "Easy burpee or sprawl-to-stand",
        kind: "conditioning",
        cue: "Skip the push-up if fatigued; land softly.",
        howToIds: ["mayo-warmup"],
      },
      cooldown: {
        name: "Walk-down + stretch",
        kind: "cooldown",
        cue: "Lower heart rate; gentle hip and shoulder mobility.",
        howToIds: ["mayo-warmup"],
      },
      instructorNote: {
        name: "Instructor / partner skill block (do not solo)",
        kind: "supervised",
        cue: "Throws, clinch, ground work, and contact defenses: only with an MAI and safety gear.",
        howToIds: ["mco-pdf", "dvids-intro-howto"],
      },
    },
    levels: {
      beginner: {
        id: "beginner",
        title: "Beginner",
        tagline: "Tan-aligned fundamentals: stance, movement, air striking, base conditioning.",
        blurb:
          "Roughly aligns with publicly described tan-belt fundamentals (stance, angles of movement) plus sustainment conditioning. Not a tan-belt course.",
        sessionMinutes: "30–45",
        prescriptions: {
          march: "3 min",
          warriorStance: "3×30–45s",
          anglesMove: "4–6 min",
          shadowLead: "3×20s",
          shadowRear: "3×20s",
          ethicsRead: "5–8 min",
          pushCond: "2×6–10",
          squatCond: "2×8–12",
          plankCond: "2×20–30s",
          cooldown: "3–5 min",
          instructorNote: "Schedule with MAI",
        },
      },
      intermediate: {
        id: "intermediate",
        title: "Intermediate",
        tagline: "Gray-aligned sustainment: cleaner footwork, combinations, harder conditioning.",
        blurb:
          "Builds on fundamentals with longer shadow strings and more conditioning volume. Contact skills remain instructor-only.",
        sessionMinutes: "40–55",
        prescriptions: {
          march: "3 min",
          warriorStance: "3×45–60s",
          anglesMove: "6–8 min",
          stanceSwitch: "4–5 min",
          comboShadow: "6–8 min",
          shadowLead: "3×30s",
          shadowRear: "3×30s",
          ethicsRead: "5 min",
          pushCond: "3×8–12",
          squatCond: "3×10–15",
          plankCond: "3×30–40s",
          burpeeLite: "2×6–8",
          cooldown: "4–6 min",
          instructorNote: "Schedule with MAI",
        },
      },
      skilled: {
        id: "skilled",
        title: "Skilled",
        tagline: "Green-and-beyond sustainment: pressure footwork, longer rounds, disciplined review.",
        blurb:
          "Higher-volume solo sustainment. Advanced MCMAP techniques and testing still require certified instructors and unit programs.",
        sessionMinutes: "45–60",
        prescriptions: {
          march: "3 min",
          warriorStance: "4×45–60s",
          anglesMove: "8–10 min",
          stanceSwitch: "5–6 min",
          comboShadow: "8–10 min",
          shadowLead: "4×30s",
          shadowRear: "4×30s",
          ethicsRead: "5–10 min",
          pushCond: "4×8–12",
          squatCond: "4×10–15",
          plankCond: "3×40–50s",
          burpeeLite: "3×8–10",
          cooldown: "5 min",
          instructorNote: "Schedule with MAI/MAIT",
        },
      },
    },
    plans: {
      beginner: {
        3: [
          {
            name: "Day 1 — Stance & movement",
            focus: "Warrior stance + angles",
            blocks: {
              warmup: ["march"],
              fundamentals: ["warriorStance", "anglesMove", "shadowLead"],
              ethos: ["ethicsRead"],
              conditioning: ["squatCond", "plankCond"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 2 — Air striking",
            focus: "Lead/rear shadow + guard recovery",
            blocks: {
              warmup: ["march"],
              fundamentals: ["warriorStance", "shadowLead", "shadowRear"],
              conditioning: ["pushCond", "plankCond"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 3 — Sustainment blend",
            focus: "Footwork + light conditioning + ethos",
            blocks: {
              warmup: ["march"],
              fundamentals: ["anglesMove", "shadowLead", "shadowRear"],
              ethos: ["ethicsRead"],
              conditioning: ["squatCond", "pushCond"],
              cooldown: ["cooldown"],
              supervised: ["instructorNote"],
            },
          },
        ],
        5: [
          {
            name: "Day 1 — Stance",
            focus: "Holds and posture",
            blocks: {
              warmup: ["march"],
              fundamentals: ["warriorStance", "anglesMove"],
              conditioning: ["plankCond"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 2 — Footwork",
            focus: "Angles only",
            blocks: {
              warmup: ["march"],
              fundamentals: ["anglesMove", "warriorStance"],
              ethos: ["ethicsRead"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 3 — Striking air",
            focus: "Lead/rear",
            blocks: {
              warmup: ["march"],
              fundamentals: ["shadowLead", "shadowRear", "warriorStance"],
              conditioning: ["pushCond"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 4 — Conditioning",
            focus: "Support fitness",
            blocks: {
              warmup: ["march"],
              fundamentals: ["warriorStance"],
              conditioning: ["squatCond", "pushCond", "plankCond"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 5 — Blend",
            focus: "Short full session",
            blocks: {
              warmup: ["march"],
              fundamentals: ["anglesMove", "shadowLead"],
              ethos: ["ethicsRead"],
              conditioning: ["squatCond"],
              cooldown: ["cooldown"],
              supervised: ["instructorNote"],
            },
          },
        ],
      },
      intermediate: {
        3: [
          {
            name: "Day 1 — Movement pressure",
            focus: "Angles + switches",
            blocks: {
              warmup: ["march"],
              fundamentals: ["warriorStance", "anglesMove", "stanceSwitch"],
              conditioning: ["burpeeLite", "plankCond"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 2 — Combinations",
            focus: "Shadow strings",
            blocks: {
              warmup: ["march"],
              fundamentals: ["comboShadow", "shadowLead", "shadowRear"],
              ethos: ["ethicsRead"],
              conditioning: ["pushCond"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 3 — Full sustainment",
            focus: "Blend + conditioning",
            blocks: {
              warmup: ["march"],
              fundamentals: ["anglesMove", "comboShadow", "stanceSwitch"],
              conditioning: ["squatCond", "pushCond", "burpeeLite"],
              cooldown: ["cooldown"],
              supervised: ["instructorNote"],
            },
          },
        ],
        5: [
          {
            name: "Day 1 — Stance endurance",
            focus: "Longer holds",
            blocks: {
              warmup: ["march"],
              fundamentals: ["warriorStance", "stanceSwitch"],
              conditioning: ["plankCond"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 2 — Footwork rounds",
            focus: "Angles",
            blocks: {
              warmup: ["march"],
              fundamentals: ["anglesMove", "stanceSwitch"],
              ethos: ["ethicsRead"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 3 — Combo rounds",
            focus: "Shadow",
            blocks: {
              warmup: ["march"],
              fundamentals: ["comboShadow", "shadowLead", "shadowRear"],
              conditioning: ["pushCond"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 4 — Hard conditioning",
            focus: "Fitness support",
            blocks: {
              warmup: ["march"],
              fundamentals: ["warriorStance"],
              conditioning: ["squatCond", "burpeeLite", "plankCond"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 5 — Integration",
            focus: "Movement + strikes",
            blocks: {
              warmup: ["march"],
              fundamentals: ["anglesMove", "comboShadow"],
              conditioning: ["pushCond", "squatCond"],
              cooldown: ["cooldown"],
              supervised: ["instructorNote"],
            },
          },
        ],
      },
      skilled: {
        3: [
          {
            name: "Day 1 — Dense footwork",
            focus: "Angles under fatigue",
            blocks: {
              warmup: ["march"],
              fundamentals: ["anglesMove", "stanceSwitch", "warriorStance"],
              conditioning: ["burpeeLite", "plankCond"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 2 — Long shadow rounds",
            focus: "Combinations",
            blocks: {
              warmup: ["march"],
              fundamentals: ["comboShadow", "shadowLead", "shadowRear"],
              ethos: ["ethicsRead"],
              conditioning: ["pushCond", "squatCond"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 3 — Peak sustainment",
            focus: "Full blend",
            blocks: {
              warmup: ["march"],
              fundamentals: ["anglesMove", "comboShadow", "stanceSwitch"],
              conditioning: ["burpeeLite", "pushCond", "plankCond"],
              cooldown: ["cooldown"],
              supervised: ["instructorNote"],
            },
          },
        ],
        5: [
          {
            name: "Day 1 — Stance & switch",
            focus: "Base",
            blocks: {
              warmup: ["march"],
              fundamentals: ["warriorStance", "stanceSwitch"],
              conditioning: ["plankCond"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 2 — Footwork volume",
            focus: "Angles",
            blocks: {
              warmup: ["march"],
              fundamentals: ["anglesMove", "stanceSwitch"],
              ethos: ["ethicsRead"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 3 — Strike volume",
            focus: "Shadow",
            blocks: {
              warmup: ["march"],
              fundamentals: ["comboShadow", "shadowLead", "shadowRear"],
              conditioning: ["pushCond"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 4 — Conditioning peak",
            focus: "Support",
            blocks: {
              warmup: ["march"],
              fundamentals: ["warriorStance"],
              conditioning: ["squatCond", "burpeeLite", "pushCond", "plankCond"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 5 — Integration",
            focus: "All tools",
            blocks: {
              warmup: ["march"],
              fundamentals: ["anglesMove", "comboShadow", "stanceSwitch"],
              conditioning: ["burpeeLite"],
              cooldown: ["cooldown"],
              supervised: ["instructorNote"],
            },
          },
        ],
      },
    },
  },

  krav: {
    id: "krav",
    title: "Krav Maga",
    shortTitle: "Krav Maga",
    tagline: "Practical self-defense fundamentals—train principles with qualified coaches.",
    blurb:
      "Solo plans cover stance, movement, and shadow striking using public beginner curriculum themes (e.g. IKMF/KMG practitioner basics). Defenses against grabs, weapons, and ground fighting require a qualified instructor and a safe training environment.",
    sources: [
      {
        id: "ikmf-curriculum",
        title: "IKMF curriculum overview (units & safety)",
        org: "IKMF (affiliate overview)",
        url: "https://kravmaga.gr/en/krav-maga/krav-maga-material.html",
        note: "Lists curriculum units including safety in training and basics (stances, punches, falls).",
      },
      {
        id: "ikmf-shop-p1",
        title: "IKMF Practitioner Level 1 materials",
        org: "IKMF official shop",
        url: "https://webshop.kravmaga-ikmf.com/practitioner-level-1-dvd-2020.html",
        note: "Official P1 topical list: stances, strikes, defenses, falls—learn with certified instructors.",
      },
      {
        id: "maxkrav-stances",
        title: "Ready stances & movements (P1 syllabus notes)",
        org: "MaxKravMaga (Eyal Yanilov lineage materials)",
        url: "https://www.maxkravmaga.com/video/ready-stances-and-movements-p1-training-syllabus/",
        note: "Public syllabus notes for outlet/ready stance and movement.",
      },
      {
        id: "maxkrav-strikes",
        title: "Straight strikes (P1 syllabus notes)",
        org: "MaxKravMaga",
        url: "https://www.maxkravmaga.com/video/straight-strikes-p1-training-syllabus/",
        note: "Palm-heel and straight punch principles; recoil emphasized.",
      },
      {
        id: "kmw-punch",
        title: "Straight punch power basics",
        org: "Krav Maga Worldwide (school article)",
        url: "https://kravmagalosangeles.com/learn-how-to-throw-a-powerful-straight-punch/",
        note: "Stance alignment and body rotation cues for straight punches.",
      },
      {
        id: "cdc-adults",
        title: "Adult Activity Overview",
        org: "CDC",
        url: "https://www.cdc.gov/physical-activity-basics/guidelines/adults.html",
        note: "General conditioning safety baseline.",
      },
    ],
    howTos: [
      {
        id: "howcast-stance",
        type: "video",
        title: "How to do the Krav Maga basic stance",
        org: "Howcast / Krav Maga Defense",
        url: "https://howcast.com/videos/509342-how-to-do-the-basic-stance-krav-maga-defense/",
      },
      {
        id: "gmau-intro",
        type: "video",
        title: "Introduction class — stance & palm strike",
        org: "Global Martial Arts University",
        url: "https://www.youtube.com/watch?v=jMMX9AuBiFc",
      },
      {
        id: "maxkrav-stances",
        type: "article",
        title: "Ready stances & movements (P1)",
        org: "MaxKravMaga",
        url: "https://www.maxkravmaga.com/video/ready-stances-and-movements-p1-training-syllabus/",
      },
      {
        id: "maxkrav-strikes",
        type: "article",
        title: "Straight strikes (P1)",
        org: "MaxKravMaga",
        url: "https://www.maxkravmaga.com/video/straight-strikes-p1-training-syllabus/",
      },
      {
        id: "kmw-punch",
        type: "article",
        title: "Straight punch mechanics article",
        org: "Krav Maga Worldwide school",
        url: "https://kravmagalosangeles.com/learn-how-to-throw-a-powerful-straight-punch/",
      },
      {
        id: "ikmf-safety",
        type: "article",
        title: "IKMF curriculum — safety & warm-up units",
        org: "IKMF curriculum overview",
        url: "https://kravmaga.gr/en/krav-maga/krav-maga-material.html",
      },
      {
        id: "ikmf-shop-p1",
        type: "article",
        title: "IKMF Practitioner Level 1 topic list",
        org: "IKMF official shop",
        url: "https://webshop.kravmaga-ikmf.com/practitioner-level-1-dvd-2020.html",
      },
      {
        id: "ace-plank",
        type: "article",
        title: "Front plank",
        org: "ACE",
        url: "https://www.acefitness.org/resources/everyone/exercise-library/32/front-plank/",
      },
      {
        id: "ace-squat",
        type: "article",
        title: "Bodyweight squat",
        org: "ACE",
        url: "https://www.acefitness.org/resources/everyone/exercise-library/135/bodyweight-squat/",
      },
      {
        id: "mayo-warmup",
        type: "article",
        title: "Warm up and cool down",
        org: "Mayo Clinic",
        url: "https://www.mayoclinic.org/healthy-lifestyle/fitness/in-depth/exercise/art-20045517",
      },
    ],
    safetyBullets: [
      "Krav Maga is a self-defense system. This site is not a federation course and does not grade practitioner levels.",
      "IKMF and similar curricula emphasize safety in training, warm-ups, and studio behavior—follow your school’s rules.",
      "Solo work here is stance, footwork, and air/shadow striking. Partner defenses, falls, ground work, and weapons defenses need a qualified instructor.",
      "Make a proper fist only when striking pads under coaching; for air practice prefer open-hand palm-heel patterns if wrists are sensitive.",
      "Stop for sharp pain; seek medical care for injuries. Self-defense legally and ethically emphasizes escape and safety—not aggression for its own sake.",
    ],
    exercises: {
      march: {
        name: "Warm-up march + arm swings",
        kind: "warmup",
        cue: "Raise temperature gradually before stance work.",
        howToIds: ["mayo-warmup", "ikmf-safety"],
      },
      outletStance: {
        name: "Outlet / ready stance hold",
        kind: "fundamentals",
        cue: "Feet roughly walking-stance width, knees soft, hands up, chin slightly down.",
        howToIds: ["howcast-stance", "maxkrav-stances", "gmau-intro"],
      },
      kravMove: {
        name: "Movement from ready stance",
        kind: "fundamentals",
        cue: "Step and glide while keeping hands protective; scan after resets.",
        howToIds: ["maxkrav-stances", "howcast-stance"],
      },
      palmHeel: {
        name: "Palm-heel straight strikes (air/pad)",
        kind: "fundamentals",
        cue: "Recoil fast; rotate hips. Prefer pads when available.",
        howToIds: ["maxkrav-strikes", "gmau-intro"],
      },
      straightPunch: {
        name: "Straight punch shadow (form focus)",
        kind: "fundamentals",
        cue: "Two large knuckles aligned; body throws the punch. Air or soft pad only.",
        howToIds: ["maxkrav-strikes", "kmw-punch"],
      },
      elbowAir: {
        name: "Elbow strike paths (air only)",
        kind: "fundamentals",
        cue: "Short, tight arcs; do not slam into hard objects.",
        howToIds: ["gmau-intro", "ikmf-safety"],
      },
      kneeAir: {
        name: "Knee drive paths (air only)",
        kind: "fundamentals",
        cue: "Hands for balance; controlled hip drive; no partner contact.",
        howToIds: ["ikmf-safety"],
      },
      comboKrav: {
        name: "Basic attack combination (shadow)",
        kind: "fundamentals",
        cue: "Palm/punch → elbow or knee path → move offline and scan.",
        howToIds: ["maxkrav-strikes", "maxkrav-stances"],
      },
      awarenessDrill: {
        name: "Awareness & exit planning (dry practice)",
        kind: "ethos",
        cue: "Pick a room: note exits, barriers, and a verbal boundary phrase. No physical contact.",
        howToIds: ["ikmf-safety"],
      },
      fallNote: {
        name: "Fall-break familiarization (instructor required)",
        kind: "supervised",
        cue: "Do not teach yourself breakfalls from videos alone—learn progressive falls with a coach on mats.",
        howToIds: ["ikmf-safety", "maxkrav-stances"],
      },
      defenseNote: {
        name: "Defense lab (chokes/grabs) — supervised only",
        kind: "supervised",
        cue: "Partner defenses belong in class with control and tapping culture.",
        howToIds: ["ikmf-safety", "ikmf-shop-p1"],
      },
      squatCond: {
        name: "Squat conditioning",
        kind: "conditioning",
        cue: "Support athletic stance strength.",
        howToIds: ["ace-squat"],
      },
      plankCond: {
        name: "Plank conditioning",
        kind: "conditioning",
        cue: "Trunk stability for striking posture.",
        howToIds: ["ace-plank"],
      },
      cooldown: {
        name: "Cool-down walk + mobility",
        kind: "cooldown",
        cue: "Ease down; breathe.",
        howToIds: ["mayo-warmup"],
      },
    },
    levels: {
      beginner: {
        id: "beginner",
        title: "Beginner",
        tagline: "P1-flavored basics: stance, movement, straight strikes in air.",
        blurb:
          "Mirrors common practitioner-1 themes (stance, movement, straight strikes) without claiming IKMF/KMG rank.",
        sessionMinutes: "30–45",
        prescriptions: {
          march: "3 min",
          outletStance: "3×30–45s",
          kravMove: "4–6 min",
          palmHeel: "4×20s",
          straightPunch: "3×20s",
          awarenessDrill: "5 min",
          squatCond: "2×8–12",
          plankCond: "2×20–30s",
          cooldown: "3–5 min",
          fallNote: "Book a class",
          defenseNote: "Book a class",
        },
      },
      intermediate: {
        id: "intermediate",
        title: "Intermediate",
        tagline: "Combinations, elbows/knees paths, sharper movement.",
        blurb:
          "More combination volume and athletic conditioning. Partner defenses remain class-only.",
        sessionMinutes: "40–55",
        prescriptions: {
          march: "3 min",
          outletStance: "3×45–60s",
          kravMove: "6–8 min",
          palmHeel: "4×30s",
          straightPunch: "4×30s",
          elbowAir: "3×20s",
          kneeAir: "3×20s",
          comboKrav: "6–8 min",
          awarenessDrill: "5 min",
          squatCond: "3×10–15",
          plankCond: "3×30–40s",
          cooldown: "4–6 min",
          fallNote: "Book a class",
          defenseNote: "Book a class",
        },
      },
      skilled: {
        id: "skilled",
        title: "Skilled",
        tagline: "Longer rounds, tighter combinations, disciplined review.",
        blurb:
          "Solo sustainment for experienced students. Advanced scenario and weapons work stays with certified instructors.",
        sessionMinutes: "45–60",
        prescriptions: {
          march: "3 min",
          outletStance: "4×45–60s",
          kravMove: "8–10 min",
          palmHeel: "5×30s",
          straightPunch: "5×30s",
          elbowAir: "4×20s",
          kneeAir: "4×20s",
          comboKrav: "8–10 min",
          awarenessDrill: "5–8 min",
          squatCond: "4×10–15",
          plankCond: "3×40–50s",
          cooldown: "5 min",
          fallNote: "Book a class",
          defenseNote: "Book a class",
        },
      },
    },
    plans: {
      beginner: {
        3: [
          {
            name: "Day 1 — Stance & move",
            focus: "Ready stance fundamentals",
            blocks: {
              warmup: ["march"],
              fundamentals: ["outletStance", "kravMove", "palmHeel"],
              ethos: ["awarenessDrill"],
              conditioning: ["plankCond"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 2 — Straight strikes",
            focus: "Palm-heel and punch form",
            blocks: {
              warmup: ["march"],
              fundamentals: ["outletStance", "palmHeel", "straightPunch"],
              conditioning: ["squatCond"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 3 — Blend",
            focus: "Movement + strikes",
            blocks: {
              warmup: ["march"],
              fundamentals: ["kravMove", "palmHeel", "straightPunch"],
              ethos: ["awarenessDrill"],
              conditioning: ["squatCond", "plankCond"],
              cooldown: ["cooldown"],
              supervised: ["fallNote", "defenseNote"],
            },
          },
        ],
        5: [
          {
            name: "Day 1 — Stance",
            focus: "Holds",
            blocks: {
              warmup: ["march"],
              fundamentals: ["outletStance", "kravMove"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 2 — Movement",
            focus: "Footwork",
            blocks: {
              warmup: ["march"],
              fundamentals: ["kravMove", "outletStance"],
              ethos: ["awarenessDrill"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 3 — Palm-heel",
            focus: "Straight open-hand",
            blocks: {
              warmup: ["march"],
              fundamentals: ["palmHeel", "outletStance"],
              conditioning: ["plankCond"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 4 — Punch form",
            focus: "Fist mechanics carefully",
            blocks: {
              warmup: ["march"],
              fundamentals: ["straightPunch", "palmHeel"],
              conditioning: ["squatCond"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 5 — Blend",
            focus: "Put it together",
            blocks: {
              warmup: ["march"],
              fundamentals: ["kravMove", "palmHeel", "straightPunch"],
              conditioning: ["plankCond"],
              cooldown: ["cooldown"],
              supervised: ["fallNote"],
            },
          },
        ],
      },
      intermediate: {
        3: [
          {
            name: "Day 1 — Athletic movement",
            focus: "Stance under motion",
            blocks: {
              warmup: ["march"],
              fundamentals: ["outletStance", "kravMove", "comboKrav"],
              conditioning: ["squatCond"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 2 — Strike toolbox",
            focus: "Palm, punch, elbow, knee paths",
            blocks: {
              warmup: ["march"],
              fundamentals: ["palmHeel", "straightPunch", "elbowAir", "kneeAir"],
              ethos: ["awarenessDrill"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 3 — Combinations",
            focus: "Strings + conditioning",
            blocks: {
              warmup: ["march"],
              fundamentals: ["comboKrav", "kravMove"],
              conditioning: ["squatCond", "plankCond"],
              cooldown: ["cooldown"],
              supervised: ["defenseNote"],
            },
          },
        ],
        5: [
          {
            name: "Day 1 — Stance endurance",
            focus: "Ready position",
            blocks: {
              warmup: ["march"],
              fundamentals: ["outletStance", "kravMove"],
              conditioning: ["plankCond"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 2 — Hand strikes",
            focus: "Palm & punch",
            blocks: {
              warmup: ["march"],
              fundamentals: ["palmHeel", "straightPunch"],
              ethos: ["awarenessDrill"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 3 — Elbows & knees",
            focus: "Short power paths",
            blocks: {
              warmup: ["march"],
              fundamentals: ["elbowAir", "kneeAir", "outletStance"],
              conditioning: ["squatCond"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 4 — Combos",
            focus: "Link tools",
            blocks: {
              warmup: ["march"],
              fundamentals: ["comboKrav", "kravMove"],
              conditioning: ["plankCond"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 5 — Integration",
            focus: "Full solo session",
            blocks: {
              warmup: ["march"],
              fundamentals: ["kravMove", "comboKrav", "straightPunch"],
              conditioning: ["squatCond"],
              cooldown: ["cooldown"],
              supervised: ["fallNote", "defenseNote"],
            },
          },
        ],
      },
      skilled: {
        3: [
          {
            name: "Day 1 — Pressure footwork",
            focus: "Long movement rounds",
            blocks: {
              warmup: ["march"],
              fundamentals: ["kravMove", "outletStance", "comboKrav"],
              conditioning: ["plankCond"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 2 — Dense combinations",
            focus: "All striking paths",
            blocks: {
              warmup: ["march"],
              fundamentals: ["palmHeel", "straightPunch", "elbowAir", "kneeAir", "comboKrav"],
              ethos: ["awarenessDrill"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 3 — Peak solo",
            focus: "Volume + discipline",
            blocks: {
              warmup: ["march"],
              fundamentals: ["kravMove", "comboKrav"],
              conditioning: ["squatCond", "plankCond"],
              cooldown: ["cooldown"],
              supervised: ["defenseNote"],
            },
          },
        ],
        5: [
          {
            name: "Day 1 — Stance",
            focus: "Base",
            blocks: {
              warmup: ["march"],
              fundamentals: ["outletStance", "kravMove"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 2 — Hands",
            focus: "Straight attacks",
            blocks: {
              warmup: ["march"],
              fundamentals: ["palmHeel", "straightPunch", "comboKrav"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 3 — Close-range paths",
            focus: "Elbows & knees",
            blocks: {
              warmup: ["march"],
              fundamentals: ["elbowAir", "kneeAir", "comboKrav"],
              conditioning: ["plankCond"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 4 — Conditioning support",
            focus: "Athleticism",
            blocks: {
              warmup: ["march"],
              fundamentals: ["outletStance"],
              conditioning: ["squatCond", "plankCond"],
              ethos: ["awarenessDrill"],
              cooldown: ["cooldown"],
            },
          },
          {
            name: "Day 5 — Integration",
            focus: "Full toolbox",
            blocks: {
              warmup: ["march"],
              fundamentals: ["kravMove", "comboKrav", "straightPunch"],
              conditioning: ["squatCond"],
              cooldown: ["cooldown"],
              supervised: ["fallNote", "defenseNote"],
            },
          },
        ],
      },
    },
  },
};
